/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import bl.Mitarbeiter;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Domi
 */
public class NewMitarbeiter extends javax.swing.JDialog {

    /**
     * Creates new form NewMitarbeiter
     */
    public boolean isOk;
    private String vorname, nachname, gebdatum, passwort;
    private SimpleDateFormat dateformat;
    public Mitarbeiter m;

    public NewMitarbeiter(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        isOk = false;
        dateformat = new SimpleDateFormat("dd.MM.yyyy");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfvorname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfnachname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfgebdatum = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfpasswort = new javax.swing.JPasswordField();
        btncreateAccount = new javax.swing.JButton();
        btnabbrechen = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(5, 2));

        jLabel1.setText("Vorname:");
        getContentPane().add(jLabel1);
        getContentPane().add(tfvorname);

        jLabel2.setText("Nachname:");
        getContentPane().add(jLabel2);
        getContentPane().add(tfnachname);

        jLabel3.setText("Geburtsdatum (dd.mm.yyyy):");
        getContentPane().add(jLabel3);
        getContentPane().add(tfgebdatum);

        jLabel4.setText("Passwort:");
        getContentPane().add(jLabel4);
        getContentPane().add(tfpasswort);

        btncreateAccount.setText("Account erstellen");
        btncreateAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncreateAccountActionPerformed(evt);
            }
        });
        getContentPane().add(btncreateAccount);

        btnabbrechen.setText("Abbrechen");
        btnabbrechen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnabbrechenActionPerformed(evt);
            }
        });
        getContentPane().add(btnabbrechen);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncreateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncreateAccountActionPerformed
       //"Baut" einen Mitarbeiter aus den Eingegebenen Daten zusammen,
       //welcher dann von der StartGUI abgefragt wird
        if (tfvorname.getText() != null && !tfvorname.getText().equals("")
                && tfnachname.getText() != null && !tfnachname.getText().equals("")
                && this.tfgebdatum.getText() != null && !tfgebdatum.getText().equals("")
                && tfgebdatum.getText().charAt(2) == '.' && tfgebdatum.getText().charAt(5) == '.' && tfgebdatum.getText().length() == 10
                && tfpasswort.getPassword() != null && !tfpasswort.getPassword().equals("")) {
            vorname = tfvorname.getText();
            nachname = tfnachname.getText();
            gebdatum = tfgebdatum.getText();
            passwort = new String(tfpasswort.getPassword());
            Date d = new Date();
            try {
                m = new Mitarbeiter(vorname, nachname, dateformat.parse(gebdatum), passwort);
            } catch (ParseException ex) {
                Logger.getLogger(NewMitarbeiter.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.isOk = true;
            this.setVisible(false);
        }

    }//GEN-LAST:event_btncreateAccountActionPerformed

    private void btnabbrechenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnabbrechenActionPerformed
        //Sperrt den Zugriff auf das Mitarbeiter- Objekt und schließt den Dialog
        this.isOk = false;
        dispose();
    }//GEN-LAST:event_btnabbrechenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewMitarbeiter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewMitarbeiter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewMitarbeiter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewMitarbeiter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NewMitarbeiter dialog = new NewMitarbeiter(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnabbrechen;
    private javax.swing.JButton btncreateAccount;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField tfgebdatum;
    private javax.swing.JTextField tfnachname;
    private javax.swing.JPasswordField tfpasswort;
    private javax.swing.JTextField tfvorname;
    // End of variables declaration//GEN-END:variables
}
